on: push
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      # Upload source code to server
      - name: 📂 Sync code to server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: dashboard.urosdeveloper.com
          username: urosdeve
          port: 2217
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/urosdeve/dashboard.urosdeveloper.com"
          exclude: |
            node_modules/
            vendor/
            storage/
            .git/
            .github/

      # Run Composer and npm directly on server
      - name: ⚡ Install dependencies on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: dashboard.urosdeveloper.com
          username: urosdeve
          port: 2217
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/urosdeve/dashboard.urosdeveloper.com
            composer install --no-dev --optimize-autoloader
            npm install
            npm run build
