on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      - name: Use Latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📂 Sync files with cleanup
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.urosdeveloper.com
          username: urosdeve@dashboard.urosdeveloper.com
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          exclude: |
            .env
          dangerous-clean-slate: true
